name: Branch Protection

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  protect-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch protection
        uses: actions/github-script@v6
        with:
          script: |
            const { data: branch } = await github.rest.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: context.ref.replace('refs/heads/', '')
            });
            
            if (!branch.protected) {
              console.log('Warning: Branch is not protected. Please enable branch protection rules in repository settings.');
            }
            
            // Check if PR has required reviews
            if (context.eventName === 'pull_request') {
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number
              });
              
              if (!pr.merged && !pr.draft) {
                const { data: reviews } = await github.rest.pulls.listReviews({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number
                });
                
                const approvedReviews = reviews.filter(review => review.state === 'APPROVED');
                if (approvedReviews.length === 0) {
                  core.setFailed('Pull request requires at least one approval before merging.');
                }
              }
            }

  enforce-signed-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check commit signatures
        run: |
          # Get the latest commit
          COMMIT_HASH=$(git rev-parse HEAD)
          
          # Check if the commit is signed
          if ! git verify-commit $COMMIT_HASH 2>/dev/null; then
            echo "::error::Commit $COMMIT_HASH is not signed with GPG"
            echo "::warning::Please sign your commits using GPG. Follow these steps:"
            echo "1. Generate a GPG key: gpg --full-generate-key"
            echo "2. List your GPG keys: gpg --list-secret-keys --keyid-format LONG"
            echo "3. Export your GPG key: gpg --armor --export YOUR_KEY_ID"
            echo "4. Add the key to your GitHub account: Settings -> SSH and GPG keys -> New GPG key"
            echo "5. Configure Git to use your GPG key: git config --global user.signingkey YOUR_KEY_ID"
            echo "6. Enable commit signing: git config --global commit.gpgsign true"
            exit 1
          fi
          
          echo "✓ Commit $COMMIT_HASH is properly signed"

  prevent-force-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Check for force push
        run: |
          if [[ "${{ github.event.forced }}" == "true" ]]; then
            echo "::error::Force pushing to protected branch is not allowed"
            echo "::warning::Please create a new branch and submit a pull request instead"
            exit 1
          fi 